import type {
  User, Business, Category, Vendor, Transaction, AdvanceRequest,
  SettlementEntry, BankAccount, Budget, Employee, TaskTemplate,
  DailyTask, AuditLog, DashboardMetrics, ApprovalChain,
} from '../types';

// ── Business ──────────────────────────────────────────────

export const MOCK_BUSINESS: Business = {
  id: 'biz-001',
  name: 'Aegean Trading Co.',
  country_code: 'IN',
  base_currency: 'INR',
  tax_regime: 'GST',
  fiscal_year_start: '04-01',
  gstin: '29ABCDE1234F1Z5',
  created_at: '2024-01-01T00:00:00Z',
};

// ── Users ─────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: 'user-001',
    business_id: 'biz-001',
    email: 'admin@aegean.com',
    name: 'Arjun Mehta',
    role: 'admin',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-002',
    business_id: 'biz-001',
    email: 'accountant@aegean.com',
    name: 'Priya Sharma',
    role: 'accountant',
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user-003',
    business_id: 'biz-001',
    email: 'manager@aegean.com',
    name: 'Rahul Verma',
    role: 'manager',
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user-004',
    business_id: 'biz-001',
    email: 'cashctrl@aegean.com',
    name: 'Sunita Patel',
    role: 'cash_controller',
    is_active: true,
    created_at: '2024-02-15T00:00:00Z',
  },
];

// ── Categories ────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-001', business_id: 'biz-001', name: 'Office Supplies', type: 'expense', color: '#6366f1', icon: 'briefcase' },
  { id: 'cat-002', business_id: 'biz-001', name: 'Travel & Transport', type: 'expense', color: '#f59e0b', icon: 'plane' },
  { id: 'cat-003', business_id: 'biz-001', name: 'Utilities', type: 'expense', color: '#10b981', icon: 'zap' },
  { id: 'cat-004', business_id: 'biz-001', name: 'Marketing', type: 'expense', color: '#ec4899', icon: 'megaphone' },
  { id: 'cat-005', business_id: 'biz-001', name: 'Rent', type: 'expense', color: '#8b5cf6', icon: 'home' },
  { id: 'cat-006', business_id: 'biz-001', name: 'Salaries', type: 'expense', color: '#ef4444', icon: 'users' },
  { id: 'cat-007', business_id: 'biz-001', name: 'Sales Revenue', type: 'income', color: '#22c55e', icon: 'trending-up' },
  { id: 'cat-008', business_id: 'biz-001', name: 'Service Income', type: 'income', color: '#3b82f6', icon: 'dollar-sign' },
  { id: 'cat-009', business_id: 'biz-001', name: 'Capital Expenditure', type: 'expense', color: '#f97316', icon: 'tool' },
];

// ── Vendors ───────────────────────────────────────────────

export const MOCK_VENDORS: Vendor[] = [
  { id: 'ven-001', business_id: 'biz-001', name: 'ABC Properties', gstin: '29ABCDE2345F1Z6' },
  { id: 'ven-002', business_id: 'biz-001', name: 'Airtel Business', gstin: '29AIRTE5678F1Z3' },
  { id: 'ven-003', business_id: 'biz-001', name: 'OfficeMart', gstin: '29OFFMA9012F1Z8' },
  { id: 'ven-004', business_id: 'biz-001', name: 'IndiGo Airlines', gstin: '29INDIG3456F1Z1' },
  { id: 'ven-005', business_id: 'biz-001', name: 'Google Ads', gstin: undefined },
  { id: 'ven-006', business_id: 'biz-001', name: 'Tata Power', gstin: '29TATAP7890F1Z4' },
  { id: 'ven-007', business_id: 'biz-001', name: 'Tech Solutions Ltd', gstin: '29TECHS1234F1Z7' },
];

// ── Transactions ──────────────────────────────────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-001',
    business_id: 'biz-001',
    type: 'expense',
    status: 'approved',
    amount: 50000,
    currency: 'INR',
    transaction_date: '2025-01-05',
    description: 'Office rent payment - January 2025',
    vendor_id: 'ven-001',
    vendor_name: 'ABC Properties',
    category_id: 'cat-005',
    category_name: 'Rent',
    payment_mode: 'bank_transfer',
    invoice_number: 'INV-2025-001',
    tax_amount: 9000,
    tax_rate: 18,
    created_by: 'user-001',
    created_by_name: 'Arjun Mehta',
    approved_by: 'user-002',
    approved_by_name: 'Priya Sharma',
    approved_at: '2025-01-05T10:00:00Z',
    is_duplicate_flagged: false,
    version: 2,
    created_at: '2025-01-05T08:00:00Z',
    updated_at: '2025-01-05T10:00:00Z',
  },
  {
    id: 'txn-002',
    business_id: 'biz-001',
    type: 'expense',
    status: 'pending_approval',
    amount: 75000,
    currency: 'INR',
    transaction_date: '2025-01-10',
    description: 'Marketing campaign - Q1 2025',
    vendor_id: 'ven-005',
    vendor_name: 'Google Ads',
    category_id: 'cat-004',
    category_name: 'Marketing',
    payment_mode: 'card',
    invoice_number: 'GADS-20250110',
    tax_amount: 13500,
    tax_rate: 18,
    created_by: 'user-003',
    created_by_name: 'Rahul Verma',
    is_duplicate_flagged: false,
    version: 1,
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'txn-003',
    business_id: 'biz-001',
    type: 'income',
    status: 'posted',
    amount: 250000,
    currency: 'INR',
    transaction_date: '2025-01-12',
    description: 'Client payment - Project Alpha milestone',
    vendor_id: 'ven-007',
    vendor_name: 'Tech Solutions Ltd',
    category_id: 'cat-008',
    category_name: 'Service Income',
    payment_mode: 'bank_transfer',
    invoice_number: 'INV-AEGEAN-2025-012',
    tax_amount: 45000,
    tax_rate: 18,
    created_by: 'user-002',
    created_by_name: 'Priya Sharma',
    is_duplicate_flagged: false,
    version: 1,
    created_at: '2025-01-12T11:00:00Z',
    updated_at: '2025-01-12T11:00:00Z',
  },
  {
    id: 'txn-004',
    business_id: 'biz-001',
    type: 'expense',
    status: 'pending_approval',
    amount: 12500,
    currency: 'INR',
    transaction_date: '2025-01-14',
    description: 'Team travel - Mumbai client visit',
    vendor_id: 'ven-004',
    vendor_name: 'IndiGo Airlines',
    category_id: 'cat-002',
    category_name: 'Travel & Transport',
    payment_mode: 'card',
    invoice_number: '6E-20250114-001',
    tax_amount: 0,
    tax_rate: 0,
    created_by: 'user-003',
    created_by_name: 'Rahul Verma',
    is_duplicate_flagged: false,
    version: 1,
    created_at: '2025-01-14T07:00:00Z',
    updated_at: '2025-01-14T07:00:00Z',
  },
  {
    id: 'txn-005',
    business_id: 'biz-001',
    type: 'expense',
    status: 'approved',
    amount: 8500,
    currency: 'INR',
    transaction_date: '2025-01-15',
    description: 'Office supplies - stationery and printer ink',
    vendor_id: 'ven-003',
    vendor_name: 'OfficeMart',
    category_id: 'cat-001',
    category_name: 'Office Supplies',
    payment_mode: 'cash',
    invoice_number: 'OM-20250115-056',
    tax_amount: 1530,
    tax_rate: 18,
    created_by: 'user-004',
    created_by_name: 'Sunita Patel',
    approved_by: 'user-002',
    approved_by_name: 'Priya Sharma',
    approved_at: '2025-01-15T15:00:00Z',
    is_duplicate_flagged: false,
    version: 2,
    created_at: '2025-01-15T14:00:00Z',
    updated_at: '2025-01-15T15:00:00Z',
  },
  {
    id: 'txn-006',
    business_id: 'biz-001',
    type: 'expense',
    status: 'pending_approval',
    amount: 150000,
    currency: 'INR',
    transaction_date: '2025-01-16',
    description: 'New server procurement - Capital expenditure',
    vendor_id: 'ven-007',
    vendor_name: 'Tech Solutions Ltd',
    category_id: 'cat-009',
    category_name: 'Capital Expenditure',
    payment_mode: 'bank_transfer',
    invoice_number: 'TSL-INV-2025-089',
    tax_amount: 27000,
    tax_rate: 18,
    created_by: 'user-001',
    created_by_name: 'Arjun Mehta',
    is_duplicate_flagged: false,
    version: 1,
    created_at: '2025-01-16T10:00:00Z',
    updated_at: '2025-01-16T10:00:00Z',
  },
  {
    id: 'txn-007',
    business_id: 'biz-001',
    type: 'expense',
    status: 'rejected',
    amount: 35000,
    currency: 'INR',
    transaction_date: '2025-01-17',
    description: 'Team outing - dinner and entertainment',
    vendor_id: undefined,
    vendor_name: 'Restaurant XYZ',
    category_id: 'cat-004',
    category_name: 'Marketing',
    payment_mode: 'cash',
    is_duplicate_flagged: false,
    version: 2,
    created_by: 'user-003',
    created_by_name: 'Rahul Verma',
    created_at: '2025-01-17T19:00:00Z',
    updated_at: '2025-01-18T09:00:00Z',
  },
  {
    id: 'txn-008',
    business_id: 'biz-001',
    type: 'income',
    status: 'posted',
    amount: 180000,
    currency: 'INR',
    transaction_date: '2025-01-18',
    description: 'Product sales - January batch',
    category_id: 'cat-007',
    category_name: 'Sales Revenue',
    payment_mode: 'bank_transfer',
    invoice_number: 'SALES-2025-JAN-001',
    tax_amount: 32400,
    tax_rate: 18,
    created_by: 'user-002',
    created_by_name: 'Priya Sharma',
    is_duplicate_flagged: false,
    version: 1,
    created_at: '2025-01-18T16:00:00Z',
    updated_at: '2025-01-18T16:00:00Z',
  },
];

// ── Advance Requests ──────────────────────────────────────

export const MOCK_ADVANCE_REQUESTS: AdvanceRequest[] = [
  {
    id: 'adv-001',
    business_id: 'biz-001',
    user_id: 'user-003',
    user_name: 'Rahul Verma',
    requested_amount: 10000,
    approved_amount: 10000,
    settled_amount: 6000,
    purpose: 'Client visit expenses - Bangalore trip',
    status: 'partially_settled',
    required_approvers: ['user-001'],
    approval_actions: [
      {
        id: 'apr-001',
        request_id: 'adv-001',
        approver_id: 'user-001',
        approver_name: 'Arjun Mehta',
        action: 'approved',
        comment: 'Approved for client visit',
        timestamp: '2025-01-08T10:00:00Z',
      },
    ],
    created_at: '2025-01-07T09:00:00Z',
    approved_at: '2025-01-08T10:00:00Z',
    due_date: '2025-01-31T00:00:00Z',
  },
  {
    id: 'adv-002',
    business_id: 'biz-001',
    user_id: 'user-004',
    user_name: 'Sunita Patel',
    requested_amount: 25000,
    approved_amount: undefined,
    settled_amount: 0,
    purpose: 'Emergency vendor payment - petty cash replenishment',
    status: 'pending_approval',
    required_approvers: ['user-002', 'user-001'],
    approval_actions: [],
    created_at: '2025-01-16T14:00:00Z',
  },
  {
    id: 'adv-003',
    business_id: 'biz-001',
    user_id: 'user-003',
    user_name: 'Rahul Verma',
    requested_amount: 5000,
    approved_amount: 5000,
    settled_amount: 5000,
    purpose: 'Office supplies purchase - urgent',
    status: 'fully_settled',
    required_approvers: ['user-001'],
    approval_actions: [
      {
        id: 'apr-002',
        request_id: 'adv-003',
        approver_id: 'user-001',
        approver_name: 'Arjun Mehta',
        action: 'approved',
        comment: 'Approved',
        timestamp: '2025-01-03T11:00:00Z',
      },
    ],
    created_at: '2025-01-02T10:00:00Z',
    approved_at: '2025-01-03T11:00:00Z',
    due_date: '2025-01-15T00:00:00Z',
  },
];

export const MOCK_SETTLEMENTS: SettlementEntry[] = [
  {
    id: 'set-001',
    advance_request_id: 'adv-001',
    settlement_amount: 6000,
    settlement_date: '2025-01-12',
    remaining_balance: 4000,
    notes: 'Partial settlement - hotel and transport expenses',
    created_by: 'user-003',
  },
  {
    id: 'set-002',
    advance_request_id: 'adv-003',
    settlement_amount: 5000,
    settlement_date: '2025-01-10',
    remaining_balance: 0,
    notes: 'Full settlement with receipts',
    created_by: 'user-003',
  },
];

// ── Bank Accounts ─────────────────────────────────────────

export const MOCK_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank-001',
    business_id: 'biz-001',
    name: 'HDFC Current Account',
    account_number_masked: 'XXXX XXXX 4521',
    bank_name: 'HDFC Bank',
    type: 'bank',
    balance: 3523000,
    currency: 'INR',
    last_synced: '2025-01-18T08:00:00Z',
    is_active: true,
  },
  {
    id: 'bank-002',
    business_id: 'biz-001',
    name: 'ICICI Savings Account',
    account_number_masked: 'XXXX XXXX 8893',
    bank_name: 'ICICI Bank',
    type: 'bank',
    balance: 852000,
    currency: 'INR',
    last_synced: '2025-01-18T08:00:00Z',
    is_active: true,
  },
  {
    id: 'bank-003',
    business_id: 'biz-001',
    name: 'Office Petty Cash',
    account_number_masked: 'N/A',
    bank_name: 'Cash',
    type: 'petty_cash',
    balance: 48000,
    currency: 'INR',
    is_active: true,
  },
];

// ── Budgets ───────────────────────────────────────────────

export const MOCK_BUDGETS: Budget[] = [
  {
    id: 'bud-001',
    business_id: 'biz-001',
    name: 'Q1 2025 Marketing',
    category_id: 'cat-004',
    category_name: 'Marketing',
    amount: 200000,
    period_start: '2025-01-01',
    period_end: '2025-03-31',
    alert_threshold: 80,
    spent: 75000,
    remaining: 125000,
    utilization_pct: 37.5,
  },
  {
    id: 'bud-002',
    business_id: 'biz-001',
    name: 'Q1 2025 Travel',
    category_id: 'cat-002',
    category_name: 'Travel & Transport',
    amount: 100000,
    period_start: '2025-01-01',
    period_end: '2025-03-31',
    alert_threshold: 80,
    spent: 12500,
    remaining: 87500,
    utilization_pct: 12.5,
  },
  {
    id: 'bud-003',
    business_id: 'biz-001',
    name: 'FY25 Office Supplies',
    category_id: 'cat-001',
    category_name: 'Office Supplies',
    amount: 120000,
    period_start: '2024-04-01',
    period_end: '2025-03-31',
    alert_threshold: 80,
    spent: 98000,
    remaining: 22000,
    utilization_pct: 81.7,
  },
];

// ── Employees ─────────────────────────────────────────────

export const MOCK_EMPLOYEES: Employee[] = [
  { id: 'emp-001', business_id: 'biz-001', employee_code: 'E001', name: 'Vikram Singh', mobile: '9876543210', department: 'Operations', designation: 'Field Executive', is_active: true, created_at: '2024-03-01T00:00:00Z' },
  { id: 'emp-002', business_id: 'biz-001', employee_code: 'E002', name: 'Kavya Reddy', mobile: '9876543211', department: 'Operations', designation: 'Field Executive', is_active: true, created_at: '2024-03-01T00:00:00Z' },
  { id: 'emp-003', business_id: 'biz-001', employee_code: 'E003', name: 'Deepak Kumar', mobile: '9876543212', department: 'Maintenance', designation: 'Technician', is_active: true, created_at: '2024-04-01T00:00:00Z' },
  { id: 'emp-004', business_id: 'biz-001', employee_code: 'E004', name: 'Anita Desai', mobile: '9876543213', department: 'Operations', designation: 'Supervisor', is_active: true, created_at: '2024-04-01T00:00:00Z' },
];

export const MOCK_TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'tmpl-001',
    business_id: 'biz-001',
    title: 'Daily Safety Inspection',
    description: 'Perform daily safety checks on all equipment',
    category: 'safety',
    estimated_minutes: 30,
    verification_required: true,
    checklist_items: [
      { id: 'ci-001', text: 'Check electrical panels', is_mandatory: true },
      { id: 'ci-002', text: 'Inspect fire extinguishers', is_mandatory: true },
      { id: 'ci-003', text: 'Test emergency exits', is_mandatory: true },
      { id: 'ci-004', text: 'Document any anomalies', is_mandatory: false },
    ],
  },
  {
    id: 'tmpl-002',
    business_id: 'biz-001',
    title: 'Inventory Count',
    description: 'Count and record all inventory items',
    category: 'operations',
    estimated_minutes: 60,
    verification_required: true,
    checklist_items: [
      { id: 'ci-005', text: 'Count raw materials', is_mandatory: true },
      { id: 'ci-006', text: 'Count finished goods', is_mandatory: true },
      { id: 'ci-007', text: 'Report discrepancies', is_mandatory: true },
    ],
  },
];

export const MOCK_DAILY_TASKS: DailyTask[] = [
  {
    id: 'task-001',
    business_id: 'biz-001',
    template_id: 'tmpl-001',
    template: MOCK_TASK_TEMPLATES[0],
    assigned_to: 'emp-001',
    assigned_to_name: 'Vikram Singh',
    assigned_by: 'user-003',
    assigned_by_name: 'Rahul Verma',
    assigned_date: '2025-01-18',
    due_date: '2025-01-18',
    status: 'verification_pending',
    started_at: '2025-01-18T09:00:00Z',
    completed_at: '2025-01-18T09:28:00Z',
  },
  {
    id: 'task-002',
    business_id: 'biz-001',
    template_id: 'tmpl-002',
    template: MOCK_TASK_TEMPLATES[1],
    assigned_to: 'emp-002',
    assigned_to_name: 'Kavya Reddy',
    assigned_by: 'user-003',
    assigned_by_name: 'Rahul Verma',
    assigned_date: '2025-01-18',
    due_date: '2025-01-18',
    status: 'in_progress',
    started_at: '2025-01-18T10:00:00Z',
  },
  {
    id: 'task-003',
    business_id: 'biz-001',
    template_id: 'tmpl-001',
    template: MOCK_TASK_TEMPLATES[0],
    assigned_to: 'emp-003',
    assigned_to_name: 'Deepak Kumar',
    assigned_by: 'user-003',
    assigned_by_name: 'Rahul Verma',
    assigned_date: '2025-01-18',
    due_date: '2025-01-18',
    status: 'pending',
  },
];

// ── Audit Logs ────────────────────────────────────────────

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    business_id: 'biz-001',
    user_id: 'user-001',
    user_name: 'Arjun Mehta',
    action: 'approve',
    resource_type: 'transaction',
    resource_id: 'txn-001',
    changes: { before: { status: 'pending_approval' }, after: { status: 'approved' } },
    ip_address: '192.168.1.100',
    timestamp: '2025-01-05T10:00:00Z',
  },
  {
    id: 'aud-002',
    business_id: 'biz-001',
    user_id: 'user-003',
    user_name: 'Rahul Verma',
    action: 'create',
    resource_type: 'transaction',
    resource_id: 'txn-004',
    changes: { after: { amount: 12500, status: 'pending_approval' } },
    ip_address: '192.168.1.102',
    timestamp: '2025-01-14T07:00:00Z',
  },
  {
    id: 'aud-003',
    business_id: 'biz-001',
    user_id: 'user-002',
    user_name: 'Priya Sharma',
    action: 'reject',
    resource_type: 'transaction',
    resource_id: 'txn-007',
    changes: { before: { status: 'pending_approval' }, after: { status: 'rejected' } },
    ip_address: '192.168.1.101',
    timestamp: '2025-01-18T09:00:00Z',
  },
];

// ── Dashboard Metrics ─────────────────────────────────────

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  cash_position: 4423000,
  cash_position_change: 215000,
  pending_approvals_count: 3,
  pending_approvals_amount: 237500,
  unverified_expenses_count: 15,
  advance_due_amount: 4000,
  bank_recon_pending: 2,
  expense_trend: [
    { month: 'Oct', amount: 285000 },
    { month: 'Nov', amount: 320000 },
    { month: 'Dec', amount: 298000 },
    { month: 'Jan', amount: 346000 },
  ],
  cash_flow: [
    { month: 'Oct', inflow: 420000, outflow: 285000 },
    { month: 'Nov', inflow: 380000, outflow: 320000 },
    { month: 'Dec', inflow: 510000, outflow: 298000 },
    { month: 'Jan', inflow: 430000, outflow: 346000 },
  ],
  top_categories: [
    { name: 'Rent', amount: 50000, color: '#8b5cf6' },
    { name: 'Marketing', amount: 75000, color: '#ec4899' },
    { name: 'Travel', amount: 12500, color: '#f59e0b' },
    { name: 'Office Supplies', amount: 8500, color: '#6366f1' },
    { name: 'Utilities', amount: 15000, color: '#10b981' },
  ],
  recent_transactions: MOCK_TRANSACTIONS.slice(0, 5),
};

// ── Approval Chains ───────────────────────────────────────

export const MOCK_APPROVAL_CHAINS: ApprovalChain[] = [
  {
    id: 'ac-001',
    business_id: 'biz-001',
    name: 'High-Value Expense Approval',
    trigger_conditions: { amount_min: 50000 },
    steps: [
      { order: 1, approvers: [{ type: 'role', value: 'manager' }], parallel: false, timeout_hours: 24 },
      { order: 2, approvers: [{ type: 'role', value: 'accountant' }, { type: 'role', value: 'admin' }], parallel: true, timeout_hours: 48 },
    ],
    is_active: true,
  },
  {
    id: 'ac-002',
    business_id: 'biz-001',
    name: 'Standard Expense Approval',
    trigger_conditions: { amount_min: 10000, amount_max: 49999 },
    steps: [
      { order: 1, approvers: [{ type: 'role', value: 'manager' }], parallel: false, timeout_hours: 24 },
    ],
    is_active: true,
  },
];
